version: '3.8'

service:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    port:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas